### ISSUE TITLE
Azure pipeline execution - process '/usr/bin/docker' failed with exit code 1

### ISSUE THREAD

**Issue by rafek1241** [mburumaxwell/paklo#176]
Error:
```
...
5c14dd7cf847: Pull complete
72c9e99967c5: Pull complete
Digest: sha256:629e24b3595b970299422de925ea1632535c166a788a1689623667c49c25f065
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.4-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.159.0/lib/dependabot/nuget/file_fetcher.rb:42:in `fetch_files': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using 'https://dev.azure.com:443/' as API endpoint
Fetching nuget dependency files for XXX/Dev/_git/XXX-example
Targeting 'master' branch under '/src' directory
Using 'auto' requirements update strategy
##[error]The process '/usr/bin/docker' failed with exit code 1
...
```
Pipeline:
```
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: dependabot@1
    inputs:
      packageManager: 'nuget'
      directory: '/src'
      targetBranch: 'master'
      versioningStrategy: 'auto'
      setAutoComplete: true
      azureDevOpsAccessToken: '$(PAT)'
      targetRepositoryName: 'XXX-example'
```

I can't see any different error than `process '/usr/bin/docker' failed with exit code 1`. Can you help me with that?

**Comment by muhmuhhum** [comment]
I have the same problem. Have you found the solution ?

**Comment by ray-kay** [comment]
My error is slightly different:

Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.4-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:471:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:467:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:396:in `_fetch_file_content'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:140:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.159.0/lib/dependabot/npm_and_yarn/file_fetcher.rb:51:in `package_json'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.159.0/lib/dependabot/npm_and_yarn/file_fetcher.rb:36:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/clients/azure.rb:237:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/clients/azure.rb:61:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:469:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:396:in `_fetch_file_content'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:140:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.159.0/lib/dependabot/npm_and_yarn/file_fetcher.rb:51:in `package_json'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.159.0/lib/dependabot/npm_and_yarn/file_fetcher.rb:36:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.159.0/lib/dependabot/file_fetchers/base.rb:65:in `files'


pipeline task:

- task: dependabot@1
  inputs:
    packageManager: 'npm'
    directory: $(npmWorkingDir)
    versioningStrategy: 'auto'
    
no npm registry used

Please advice.
Thanks

**Comment by mburumaxwell** [comment]
@ray-kay sometimes this may occur due to an issue with permissions. Could you at least try and debug using the `EXCON_DEBUG=1` options in the `extraEnvironmentVariables` input?

```yaml
- task: dependabot@1
  inputs:
    packageManager: 'npm'
    directory: '/myfolder'
    extraEnvironmentVariables: 'EXCON_DEBUG=1'
```

This will output the HTTP requests and responses being sent to Azure DevOps. They are the truth-tellers. You can post the output here for further assistance. Remember to redact anything sensitive.

**Comment by rafek1241** [comment]
@mburumaxwell 
I decided to wait for a solution and just mention that issue on repository because it's an optional feature for me.

**Comment by ray-kay** [comment]
@mburumaxwell 
thanks for your hint with the debug var.
Output:

```
  :remote_ip     => "13.107.42.18"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:471:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:467:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:396:in `_fetch_file_content'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:140:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:51:in `package_json'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:36:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/clients/azure.rb:237:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/clients/azure.rb:61:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:469:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:396:in `_fetch_file_content'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:140:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:51:in `package_json'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:36:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
Using hostname = 'asfinag.visualstudio.com', protocol = 'https', port = '443'.
Using 'https://asfinag.visualstudio.com:443/' as API endpoint
Fetching npm_and_yarn dependency files for asfinag/content/_git/content-backoffice-client
Targeting 'default' branch under './Asfinag.ContentPortal.BackOffice/Asfinag.ContentPortal.BackOffice/ClientApp' directory
Using 'bump_versions' requirements update strategy
##[error]The process '/usr/bin/docker' failed with exit code 1
```

The correct repo URL is: https://asfinag.visualstudio.com/content/_git/content-backoffice-client
but its showing host: 'asfinag.visualstudio.com' and path "asfinag/content/_git/content-backoffice-client" where "asfinag/" seems wrong.

Br

**Comment by MO2k4** [comment]
You need to use the "new" url schema dev.azure.com as the old one is not supported.

**Comment by sven5** [comment]
I'm getting this error message:

```
:host          => "dev.azure.com"
  :local_address => "172.17.0.2"
  :local_port    => 58654
  :path          => "/xxxxxx/xxx-xxxx/_apis/git/repositories/xxx-xxx/pushes"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "13.107.42.20"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/clients/azure.rb:267:in `post': Dependabot::Clients::Azure::Forbidden (Dependabot::Clients::Azure::Forbidden)
from /home/dependabot/dependabot-script/vendor/rub
```

**Comment by MO2k4** [comment]
I think you are missing some permissions

![image](https://user-images.githubusercontent.com/453360/135499403-be19ddc7-b928-4f7b-8b6a-797ddad91ba2.png)

**Comment by MartijnErmersI** [comment]
We encounter the exit code 1 also sometimes:
`2021-10-04T00:03:40.0882517Z Checking if LiteDB 4.1.4 needs updating
2021-10-04T00:03:40.0882807Z Requirements to unlock own
2021-10-04T00:03:40.0883090Z Updating LiteDB from 4.1.4 to 5.0.11
2021-10-04T00:03:40.0883494Z Submitting LiteDB pull request for creation. Failed! PR already exists or an error has occurred.
2021-10-04T00:03:40.2359467Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2021-10-04T00:03:40.2389960Z ##[section]Finishing: dependabot`

The problem in our case is caused by a **wrong case issue** of references in the .sln files to .csproj files. Other parts of the build do not have a problem with this, because other parts are run in Windows (case insensitive file system).

If more people encounter this casing issue. Perhaps it's a good idea to add a check to this extension that pre-checks on casing issues and report clearly that that is the issue.

**Comment by ray-kay** [comment]
Thanks @sven5 
sorry for this question but:
Where do I find the docs for granting permissions for dependabot in Azure Devops?

**Comment by AurimasNav** [comment]
If using `targetRepositoryName` to check other repos, in addition to build agent permissions I also had to disable [`rotect access to repositories in YAML pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#job-authorization-scope) option under `project settings` -> `pipelines` -> `settings`

**Comment by SchulteMarkus** [comment]
> 

In my case, "force push" was not required for running Dependabot. I am quite happy not having to give "force" permissions. But I had to give "Contribute" permissions.

**Comment by SchulteMarkus** [comment]
> I think you are missing some permissions
> 
> ![image](https://user-images.githubusercontent.com/453360/135499403-be19ddc7-b928-4f7b-8b6a-797ddad91ba2.png)

In my case, "force push" was not required for running Dependabot. I am quite happy not having to give "force" permissions. 
But I had to give "Contribute" permissions.
